services:
  wrf-wps:
    build:
      context: ../
      dockerfile: wrf-wps-wvt-mr/Dockerfile
    image: mullenkamp/wrf-wps-wvt-mr-debian:1.0
    stdin_open: true
    tty: true
    shm_size: '2gb'   # multi-region multi-rank runs want >=2gb shared memory (more tracers per rank)
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /media/data/WRF/testing:/testing
      - wps-geog:/WPS_GEOG

volumes:
  wps-geog:
    external: true
